# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - local-ai-network
    ports:
      - "4512:8080"
    restart: always
    volumes:
      - ${DOCKER_FOLDER}/open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - USE_OLLAMA_DOCKER=true

# We create a specific network for these Docker containers to communicate over called local-ai-network
networks:
  local-ai-network:
    external: false
